//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyBot {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VerifyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal VerifyStrings() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerifyBot.VerifyStrings", typeof(VerifyStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Account is already verified. If you are having issues message a verifer.
        /// </summary>
        public static string AccountAlreadyVerified {
            get {
                return ResourceManager.GetString("AccountAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to API Key account does not match supplied account name..
        /// </summary>
        public static string AccountNameDoesNotMatch {
            get {
                return ResourceManager.GetString("AccountNameDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Could not find that account in the GW2 API..
        /// </summary>
        public static string AccountNotInAPI {
            get {
                return ResourceManager.GetString("AccountNotInAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Account is not on a valid server..
        /// </summary>
        public static string AccountNotOnServer {
            get {
                return ResourceManager.GetString("AccountNotOnServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Verification Process Complete. Welcome!.
        /// </summary>
        public static string EndMessage {
            get {
                return ResourceManager.GetString("EndMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error processing your verification request. Please try again..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Respond to this bot with the following information: {account-name} {api-key} (Without the { or } characters).
        /// </summary>
        public static string InitialMessage {
            get {
                return ResourceManager.GetString("InitialMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Bad API Key.
        /// </summary>
        public static string InvalidAPIKey {
            get {
                return ResourceManager.GetString("InvalidAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Could not parse your response..
        /// </summary>
        public static string ParseError {
            get {
                return ResourceManager.GetString("ParseError", resourceCulture);
            }
        }
    }
}
